module.exports = {
  introSidebar: [{type: 'autogenerated', dirName: 'intro'}],
  miscSidebar: [{type: 'autogenerated', dirName: 'misc'}],
  platformsSidebar: [{type: 'autogenerated', dirName: 'platforms'}]
};
