module.exports = {
  introSidebar: [{type: 'autogenerated', dirName: 'docs/intro'}],
  miscSidebar: [{type: 'autogenerated', dirName: 'docs/misc'}],
  platformsSidebar: [{type: 'autogenerated', dirName: 'docs/platforms'}]
};
